/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package jpcap;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author DELL
 */
public final class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
        m();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setText("X");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 30, 30));

        jLabel2.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 30, 30));

        jLabel3.setBackground(new java.awt.Color(153, 153, 0));
        jLabel3.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("X");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 30, 30));

        jLabel4.setBackground(new java.awt.Color(153, 153, 0));
        jLabel4.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 255));
        jLabel4.setText("X");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 30, 30));

        jLabel5.setBackground(new java.awt.Color(153, 153, 0));
        jLabel5.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 255));
        jLabel5.setText("X");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 30, 30));

        jLabel6.setBackground(new java.awt.Color(153, 153, 0));
        jLabel6.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 255));
        jLabel6.setText("X");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 30, 30));

        jLabel7.setBackground(new java.awt.Color(153, 153, 0));
        jLabel7.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 255));
        jLabel7.setText("X");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 30, 30));

        jLabel8.setBackground(new java.awt.Color(153, 153, 0));
        jLabel8.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 255));
        jLabel8.setText("X");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 30, 30));

        jLabel9.setBackground(new java.awt.Color(153, 153, 0));
        jLabel9.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 204, 255));
        jLabel9.setText("X");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 30, 30));

        jLabel10.setBackground(new java.awt.Color(153, 153, 0));
        jLabel10.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 255));
        jLabel10.setText("X");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 30, 30));

        jLabel11.setBackground(new java.awt.Color(153, 153, 0));
        jLabel11.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 255));
        jLabel11.setText("X");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 30, 30));

        jLabel12.setBackground(new java.awt.Color(153, 153, 0));
        jLabel12.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 255));
        jLabel12.setText("X");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 30, 30));

        jLabel13.setBackground(new java.awt.Color(153, 153, 0));
        jLabel13.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 255));
        jLabel13.setText("X");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 30, 30));

        jLabel14.setBackground(new java.awt.Color(153, 153, 0));
        jLabel14.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 255));
        jLabel14.setText("X");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 30, 30));

        jLabel15.setBackground(new java.awt.Color(153, 153, 0));
        jLabel15.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 255));
        jLabel15.setText("X");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 30, 30));

        jLabel16.setBackground(new java.awt.Color(153, 153, 0));
        jLabel16.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(204, 204, 255));
        jLabel16.setText("X");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 30, 30));

        jLabel17.setBackground(new java.awt.Color(153, 153, 0));
        jLabel17.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 255));
        jLabel17.setText("X");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 30, 30));

        jLabel18.setBackground(new java.awt.Color(153, 153, 0));
        jLabel18.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 255));
        jLabel18.setText("X");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 30, 30));

        jLabel19.setBackground(new java.awt.Color(153, 153, 0));
        jLabel19.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(204, 204, 255));
        jLabel19.setText("X");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 30, 30));

        jLabel20.setBackground(new java.awt.Color(153, 153, 0));
        jLabel20.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 255));
        jLabel20.setText("X");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 30, 30));

        jLabel21.setBackground(new java.awt.Color(153, 153, 0));
        jLabel21.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(204, 204, 255));
        jLabel21.setText("X");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 30, 30));

        jLabel22.setBackground(new java.awt.Color(153, 153, 0));
        jLabel22.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(204, 204, 255));
        jLabel22.setText("X");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 30, 30));

        jLabel23.setBackground(new java.awt.Color(153, 153, 0));
        jLabel23.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(204, 204, 255));
        jLabel23.setText("X");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 30, 30));

        jLabel24.setBackground(new java.awt.Color(153, 153, 0));
        jLabel24.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 204, 255));
        jLabel24.setText("X");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 150, 30, 30));

        jLabel25.setBackground(new java.awt.Color(153, 153, 0));
        jLabel25.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(204, 204, 255));
        jLabel25.setText("X");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 30, 30));

        jLabel26.setBackground(new java.awt.Color(153, 153, 0));
        jLabel26.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(204, 204, 255));
        jLabel26.setText("X");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 30, 30));

        jLabel27.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 204, 255));
        jLabel27.setText("X");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, 30, 30));

        jLabel28.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(204, 204, 255));
        jLabel28.setText("X");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 30, 30));

        jLabel29.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(204, 204, 255));
        jLabel29.setText("X");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 280, 30, 30));

        jLabel30.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(204, 204, 255));
        jLabel30.setText("X");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 30, 30));

        jLabel31.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(204, 204, 255));
        jLabel31.setText("X");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 30, 30));

        jLabel32.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(204, 204, 255));
        jLabel32.setText("X");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, 30, 30));

        jLabel33.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(204, 204, 255));
        jLabel33.setText("X");
        getContentPane().add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 30, 30));

        jLabel34.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(204, 204, 255));
        jLabel34.setText("X");
        getContentPane().add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 30, 30));

        jLabel35.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(204, 204, 255));
        jLabel35.setText("X");
        getContentPane().add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 30, 30));

        jLabel36.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(204, 204, 255));
        jLabel36.setText("X");
        getContentPane().add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, 30, 30));

        jLabel37.setBackground(new java.awt.Color(153, 153, 0));
        jLabel37.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(204, 204, 255));
        jLabel37.setText("X");
        getContentPane().add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 450, 30, 30));

        jLabel38.setBackground(new java.awt.Color(153, 153, 0));
        jLabel38.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(204, 204, 255));
        jLabel38.setText("X");
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 440, 30, 30));

        jLabel39.setBackground(new java.awt.Color(153, 153, 0));
        jLabel39.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(204, 204, 255));
        jLabel39.setText("X");
        getContentPane().add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 30, 30));

        jLabel40.setBackground(new java.awt.Color(153, 153, 0));
        jLabel40.setFont(new java.awt.Font("DL-Anupama", 1, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(204, 204, 255));
        jLabel40.setText("X");
        getContentPane().add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 30, 30));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(0, 102, 255));
        jLabel41.setText("JCAPTOR");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 260, 70));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpcap/images/computer.jpg"))); // NOI18N
        getContentPane().add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 200, 200));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jpcap/images/light_fawn_and_blue_waves-1280x800.jpg"))); // NOI18N
        getContentPane().add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 500));

        setSize(new java.awt.Dimension(713, 537));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void m() {
        new Thread(new Runnable() {

            @Override
            public void run() {
                throw new UnsupportedOperationException("Not supported yet.");
            }
        }) {

            @Override
              public void run() {

                JLabel s[] = {jLabel1, jLabel2, jLabel3, jLabel4,jLabel5,jLabel6, jLabel7, jLabel8, jLabel9,jLabel10,jLabel11,jLabel12,jLabel13,jLabel14,jLabel15,jLabel16,jLabel17,jLabel18,jLabel19,jLabel20,jLabel21,jLabel22,jLabel23,jLabel24,jLabel25,jLabel26,jLabel27,jLabel28,jLabel29,jLabel30,jLabel31,jLabel32,jLabel33,jLabel34,jLabel35,jLabel36,jLabel37,jLabel38,jLabel39,jLabel40};

                try {

                    for (int x = ((s.length)-1); x >=0; x--) {
                        Color c = s[x].getForeground();
                        s[x].setForeground(new Color(255, 0, 0));
                        Thread.sleep(100);
                        s[x].setForeground(c);

                    }
                    new NewJFrame3().setVisible(true);
                    dispose();
                } catch (Exception e) {
                }

            }
              
        
                } .start();
}
              
        public static void main(String args[]) throws UnsupportedLookAndFeelException {
            
              try { 
       // Set System L&F 
        UIManager.setLookAndFeel( 
            UIManager.getSystemLookAndFeelClassName()); 
    } 
    
    catch (ClassNotFoundException e) { 
       // handle exception 
    } 
    catch (InstantiationException e) { 
       // handle exception 
    } 
    catch (IllegalAccessException e) { 
       // handle exception 
    } 

 
 
            
            
            
            
       java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                
                new NewJFrame().setVisible(true);
            }
        });
       
       
       
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
